// Sköll self-play sim — drives the deterministic floor through a real GameEngine across a seed sweep,
// prints the pacing metrics, and writes them to the committed corpus. The floor is the only part of
// Sköll that runs without a Gemini key, so it is the measurable proxy for his win pacing.
//
// Run: node scripts/skoll-sim.mjs [games]   (default 1000)
//
// The repo's TS modules use the SvelteKit `$lib` alias and a bare JSON import that only Vite resolves.
// This script teaches plain Node both, via module resolve/load hooks, so the sim runs with no extra
// tooling or dependencies — node + the source files, nothing else.

import { registerHooks } from 'node:module';
import { existsSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LIB = path.join(ROOT, 'src', 'lib');

function resolveAlias(rest) {
	const base = path.join(LIB, rest);
	for (const candidate of [base, `${base}.ts`, path.join(base, 'index.ts')]) {
		if (existsSync(candidate)) return candidate;
	}
	return base;
}

// SvelteKit virtual modules the sim's dependency chain touches (skoll.ts/oracle.ts read `dev`). Vite
// supplies these; plain Node needs a stub. The sim never runs in a browser or reads a real env.
const SHIMS = {
	'$app/environment': 'export const dev = false; export const browser = false;\n'
};

registerHooks({
	resolve(specifier, context, nextResolve) {
		if (specifier in SHIMS) return { url: `shim:${specifier}`, shortCircuit: true };
		if (specifier === '$lib' || specifier.startsWith('$lib/')) {
			const rest = specifier === '$lib' ? '' : specifier.slice('$lib/'.length);
			return nextResolve(pathToFileURL(resolveAlias(rest)).href, context);
		}
		// Relative TS imports are written extensionless (Vite resolves them); add the .ts Node needs.
		if (specifier.startsWith('.') && context.parentURL && !context.parentURL.startsWith('shim:')) {
			const target = new URL(specifier, context.parentURL);
			if (!existsSync(fileURLToPath(target))) {
				for (const ext of ['.ts', '/index.ts']) {
					if (existsSync(fileURLToPath(new URL(specifier + ext, context.parentURL)))) {
						return nextResolve(specifier + ext, context);
					}
				}
			}
		}
		return nextResolve(specifier, context);
	},
	load(url, context, nextLoad) {
		if (url.startsWith('shim:'))
			return { format: 'module', shortCircuit: true, source: SHIMS[url.slice('shim:'.length)] };
		// board.ts imports runes.json without an attribute — Vite injects it; Node needs it explicit.
		if (url.endsWith('.json')) context.importAttributes = { type: 'json' };
		return nextLoad(url, context);
	}
});

const { simulateFloor, BOARD_SIZE } = await import(
	pathToFileURL(path.join(LIB, 'server', 'skoll', 'sim.ts')).href
);

const DEFAULT_GAMES = 1000;
const games = parseGames(process.argv[2]);
const TARGET = { lo: 7.5, hi: 9 };

// A non-positive or non-numeric arg yields NaN/0 win rates and a garbage corpus — reject it loudly
// rather than silently writing nonsense. No arg falls back to the default sweep.
function parseGames(arg) {
	if (arg === undefined) return DEFAULT_GAMES;
	const n = Number(arg);
	if (!Number.isInteger(n) || n < 1) {
		console.error(`games must be a positive integer, got "${arg}"`);
		process.exit(1);
	}
	return n;
}
const metrics = await simulateFloor(games);
const inWindow = metrics.meanTurns >= TARGET.lo && metrics.meanTurns <= TARGET.hi;

console.log(`Sköll floor self-play — ${games} seeded games over a ${BOARD_SIZE}-rune board\n`);
console.log(`  win rate     ${(metrics.winRate * 100).toFixed(1)}%`);
console.log(`  mean turns   ${metrics.meanTurns.toFixed(2)}  (target ${TARGET.lo}–${TARGET.hi})`);
console.log(`  median turns ${metrics.medianTurns}`);
console.log(`  range        ${metrics.minTurns}–${metrics.maxTurns}`);
console.log(`  pacing       ${inWindow ? 'WITHIN target window' : 'OUT OF target window'}\n`);

const corpus = renderCorpus(metrics, games);
const corpusPath = path.join(ROOT, 'docs', 'skoll-metrics-corpus.md');
await writeFile(corpusPath, corpus, 'utf8');
console.log(`corpus written → ${path.relative(ROOT, corpusPath)}`);

function renderCorpus(m, gameCount) {
	const peak = Math.max(...m.distribution.map((d) => d.count), 1);
	const rows = m.distribution
		.map(({ turns, count }) => {
			const pct = ((count / m.wins) * 100).toFixed(1);
			const bar = '█'.repeat(Math.max(1, Math.round((count / peak) * 30)));
			return `| ${turns} | ${count} | ${pct}% | ${bar} |`;
		})
		.join('\n');

	return `# Sköll Metrics Corpus 🐺

> Generated by \`node scripts/skoll-sim.mjs\`. Do not hand-edit — re-run the script to refresh.

Self-play of Sköll's **deterministic floor** (his seeded fallback move) driven move-by-move through a
real \`GameEngine\` until he casts the secret. The floor is the only part of Sköll that runs without a
Gemini key, so it is the measurable proxy for his win pacing. **Turns-to-win counts Sköll's own moves**
(his Asks plus the winning Cast), not the engine's alternation flips.

The pacing target: Sköll's own wins average **7.5–9 turns** — slow enough that a competent human can
beat him, fast enough that he's a real threat.

## Aggregate

| metric | value |
| --- | --- |
| games (seeds) | ${gameCount} |
| board size | ${BOARD_SIZE} runes |
| win rate | ${(m.winRate * 100).toFixed(1)}% |
| mean turns-to-win | **${m.meanTurns.toFixed(2)}** |
| median turns-to-win | ${m.medianTurns} |
| min / max turns | ${m.minTurns} / ${m.maxTurns} |
| target window | 7.5–9 |
| within window | ${m.meanTurns >= 7.5 && m.meanTurns <= 9 ? 'yes ✅' : 'no ❌'} |

## Turns-to-win distribution

| turns | games | share | |
| --- | --- | --- | --- |
${rows}

## Live wolf validation (local, requires a key)

The deterministic floor above is the CI-measurable proxy. The numbers below come from driving the
**live Gemini wolf** (\`gemini-3.5-flash\`, the real \`decideSkollMove\` brain) through the same engine
loop, run locally with a \`GEMINI_API_KEY\` — never in CI, which has no key. Recorded 2026-06-13 (with
the wrong-cast memory fix, so a missed cast is never repeated):

| metric | value |
| --- | --- |
| games (seeds 1–30) | 30 |
| win rate | 100% (30/30) |
| mean turns-to-win | **8.17** |
| median turns-to-win | 8 |
| min / max turns | 5 / 14 |
| within 7.5–9 window | yes ✅ |

The live wolf and the deterministic floor land in the same window — the persona pacing holds whether
Sköll is thinking with Gemini or falling back to the seeded floor.
`;
}
